### ISSUE TITLE
operator < (BigInt const & rhs); is not const

### ISSUE THREAD

**Issue by asashnov** [DjCrush/BigIntLibrary#2]
https://github.com/DjCrush/BigIntLibrary/blob/f96c24769d6868a4d90ad88d75d5c78b1cac8843/bigint.h#L31

`	inline bool operator < (BigInt const & rhs);`
should be:
`	inline bool operator < (BigInt const & rhs) const;`

because the comparison should not modify the stored value.

**Comment by DjCrush** [comment]
Fixed
