### ISSUE TITLE
addition and 3 methods more : arguments are not const references

### ISSUE THREAD

**Issue by asashnov** [DjCrush/BigIntLibrary#3]
https://github.com/DjCrush/BigIntLibrary/blob/f96c24769d6868a4d90ad88d75d5c78b1cac8843/bigint.h#L35

Actual code:
```
	string addition(string a, string b);
	string substraction(string a, string b);
	string division(string a, string b);
        string multiplication(string a, string b);
```

Should be:
`	string addition(const string &a, const string &b);
`

to avoid extra std::string() copy constructor call (and extra memory allocation/freeing).

**Comment by DjCrush** [comment]
Not all variables are changed in these functions. And to avoid unnecessary copying they are passed by constant reference.
